version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 679209310994.dkr.ecr.us-east-2.amazonaws.com
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export ECR_URI=679209310994.dkr.ecr.us-east-2.amazonaws.com/simple-flask-app

  build:
    commands:
      - docker build -t $ECR_URI:$IMAGE_TAG ./simple-flask-app
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - printf '[{"name":"flask-pipeline","imageUri":"%s:%s"}]' $ECR_URI $IMAGE_TAG > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yml
    - taskdef.json